# Generated by Django 2.1.5 on 2019-02-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GearTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('components', models.ManyToManyField(blank=True, related_name='_material_components_+', to='character.Material')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Health', 'Health'), ('Damage', 'Damage'), ('Armor', 'Armor'), ('Focus', 'Focus'), ('Resistance', 'Resistance')], max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='material_bonuses',
            field=models.ManyToManyField(related_name='materials', to='character.MaterialBonus'),
        ),
        migrations.AddField(
            model_name='geartier',
            name='materials',
            field=models.ManyToManyField(related_name='gear_tiers', to='character.Material'),
        ),
        migrations.AddField(
            model_name='character',
            name='character_types',
            field=models.ManyToManyField(to='character.CharacterType'),
        ),
        migrations.AddField(
            model_name='character',
            name='gear_tiers',
            field=models.ManyToManyField(to='character.GearTier'),
        ),
    ]
