# Generated by Django 2.1.5 on 2019-02-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
