# Generated by Django 2.1.5 on 2019-02-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_character_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('trait_type', models.CharField(choices=[('Side', 'Side'), ('Trait', 'Trait'), ('Origin', 'Origin'), ('Team', 'Team'), ('Role', 'Role'), ('Flavor', 'Flavor')], max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='character_types',
        ),
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='traits',
            field=models.ManyToManyField(to='character.Trait'),
        ),
    ]
