# Generated by Django 2.1.5 on 2019-02-16 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_auto_20190216_2028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharacterType',
        ),
    ]
