# Generated by Django 2.1.5 on 2019-02-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_delete_charactertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='gear_tiers',
            field=models.ManyToManyField(blank=True, to='character.GearTier'),
        ),
        migrations.AlterField(
            model_name='character',
            name='traits',
            field=models.ManyToManyField(blank=True, to='character.Trait'),
        ),
    ]
