# Generated by Django 2.1.5 on 2019-02-16 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_auto_20190216_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name']},
        ),
    ]
