# Generated by Django 2.1.5 on 2019-02-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_auto_20190216_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='geartier',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.CharField(choices=[('Green', 'Green'), ('Blue', 'Blue'), ('Purple', 'Purple'), ('Orange', 'Orange')], default=('Green', 'Green'), max_length=64),
        ),
        migrations.AddField(
            model_name='material',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='materialbonus',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
