# Generated by Django 2.1.5 on 2019-02-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterinstance',
            name='current_gear_materials',
            field=models.ManyToManyField(blank=True, to='character.Material'),
        ),
    ]
