# Generated by Django 2.1.5 on 2019-02-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_auto_20190216_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterinstance',
            name='unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
