# Generated by Django 2.1.5 on 2019-02-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_characterinstance_unlocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='shareable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='characterinstance',
            name='red_stars',
            field=models.IntegerField(default=0),
        ),
    ]
