# Generated by Django 2.1.5 on 2019-02-17 00:36

from django.db import migrations
import msf_user.models


class Migration(migrations.Migration):

    dependencies = [
        ('msf_user', '0002_auto_20190216_2031'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', msf_user.models.MsfUserManager()),
            ],
        ),
    ]
